# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_auto_20171223_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='contrast_category',
            field=models.CharField(default='e', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='contrast',
            field=models.CharField(max_length=16, verbose_name='Contrast details'),
        ),
    ]
