# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20180128_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='contrast',
            field=models.CharField(max_length=32, verbose_name='Contrast details'),
        ),
    ]
