# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_remove_acquisition_dataset_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition',
            old_name='subject',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='image',
            name='contrast',
        ),
    ]
