# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0009_auto_20180322_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=512, unique=True, verbose_name='File path: (/Volumes/sct_testing/large/)'),
        ),
        migrations.AlterField(
            model_name='labeledimage',
            name='filename',
            field=models.CharField(max_length=512, unique=True, verbose_name='File path: (/Volumes/sct_testing/large/)'),
        ),
    ]
