# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0011_auto_20180326_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filestate',
            field=models.CharField(choices=[('OK', 'File is available'), ('NA', 'File not available'), ('ERR', 'File error')], default='NA', max_length=3, verbose_name='The state of the file'),
        ),
        migrations.AlterField(
            model_name='labeledimage',
            name='filestate',
            field=models.CharField(choices=[('OK', 'File is available'), ('NA', 'File not available'), ('ERR', 'File error')], default='NA', max_length=3, verbose_name='The state of the file'),
        ),
    ]
