# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0014_labeledimage_label_needs_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='end_coverage',
            field=models.CharField(choices=[('Brain', 'Brain'), ('PMJ', 'PMJ'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C6', 'C6'), ('C7', 'C6'), ('C8', 'C8'), ('', 'N/A')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='start_coverage',
            field=models.CharField(choices=[('Brain', 'Brain'), ('PMJ', 'PMJ'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C6', 'C6'), ('C7', 'C6'), ('C8', 'C8'), ('', 'N/A')], default='', max_length=16),
        ),
    ]
