# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0014_labeledimage_label_needs_correction'),
    ]

    operations = [
    migrations.RenameField('Image', 'corrinal', 'coronal'),
    ]
