# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 18:14
from __future__ import unicode_literals

from django.db import migrations
def link_center(apps, schema_editor):
    Acquisition = apps.get_model('annotations', 'Acquisition')
    CenterDictionary = apps.get_model('annotations', 'CenterDictionary')
    for center_buf in Acquisition.objects.all():
        center, created = CenterDictionary.objects.get_or_create(center_acronym=center_buf.center)
        center_buf.center_link = center
        center_buf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0015_add_center_dictionary'),
    ]

    operations = [
    migrations.RunPython(link_center)
    ]
