# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0016_transfer_center_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerdictionary',
            options={'verbose_name_plural': 'Center Dictionary'},
        ),
        migrations.AddField(
            model_name='acquisition',
            name='center_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotations.CenterDictionary'),
        ),
    ]
